Updated Travis File

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,110 +1,108 @@
-# Travis CI (MIT License) configuration file.
-# @link https://travis-ci.org/
-
-# Declare project language.
-# @link http://about.travis-ci.org/docs/user/languages/php/
+sudo: false
+dist: trusty
 language: php
-
-# Declare versions of PHP to use. Use one decimal max.
-php:
-  # aliased to a recent 5.5.x version
-  - "5.5"
-  # aliased to a recent 5.4.x version
-  - "5.4"
-  # aliased to a recent 5.3.x version
-  - "5.3"
-  # Current $required_php_version for WordPress: 5.2.4
-  - "5.2"
-
-# Declare which versions of WordPress to test against.
-# Also declare whether or not to test in Multisite.
+notifications:
+  email:
+    on_success: never
+    on_failure: change
+cache:
+  directories:
+    - vendor
+    - $HOME/.composer/cache
+after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh
+  | bash
 env:
-  # Trunk
-  # @link https://github.com/WordPress/WordPress
-  - WP_VERSION=master WP_MULTISITE=0
-  - WP_VERSION=master WP_MULTISITE=1
-  # WordPress 4.2
-  # @link https://github.com/WordPress/WordPress/tree/4.2-branch
-  - WP_VERSION=4.2 WP_MULTISITE=0
-  - WP_VERSION=4.2 WP_MULTISITE=1
-  # WordPress 4.1
-  # @link https://github.com/WordPress/WordPress/tree/4.1-branch
-  - WP_VERSION=4.1 WP_MULTISITE=0
-  - WP_VERSION=4.1 WP_MULTISITE=1
-
-# Declare 5.6 beta in test matrix.
-# @link https://buddypress.trac.wordpress.org/ticket/5620
-# @link http://docs.travis-ci.com/user/build-configuration/
+  matrix:
+  - WP_VERSION=latest WP_MULTISITE=0
+  global:
+  - WP_TRAVISCI=travis:phpunit
+  - SVN_REPO: https://plugins.svn.wordpress.org/syndication-links/
+  - GH_REF: https://github.com/dshanske/syndication-links.git
+  - secure: SKEHj0zThPfUhTyTKtgNuzqPp+uvdUUcMWT0ZqyARjnOGII6dO2UDzQIUc5WolgFd/HYIFfaDzBd3+FPdDTunPiwIHxIYcyr2EjvEQLJYM1zqTAUtjEPpztemKRtrnbNd1TQgWIIqIaNk//WuYkuW7+vc/HsyyTm6PGEbHK6zj11UG8ZYT8ru/Sw+PxHebwlz3d+8H6iEvFSX/rkc1kMpntwNMoFYb9PgwhkvtJ6KkVRKu4uMCkXf6BnlVqJSAGdTn+XckDeY+pwgsWGIAPakLD9MKxAq2MMqfmCxTK8uMN3VBetlbbkT7JMaYyU95gw3+3QrcPLlmRLNdbiuguD39J820wjtflEUNCJ3Heg8JF0q4z/69s6n3LEinDxtJNesK/0G//nYjsLaKXARFfnvLSRbhZvxeePsmEWTxEGt9KvoW7iD/vnwYmf1aYeobwBfkCkvA7t5FSNUTMvI8yo33DWdOyFKdWRL0V2JaaOh0H81kaXOEBayplmDfdbNX7y77/bLU863V0JkORSsJNv7ZGl8zR77ja/s1Ep0F3d43QhIoQk40w8SckpLEx+2bUs3J2jNpBeike5cut7RuSPTt7G2AiipTfmPa666f+CsmfNAjd2MYFfB2NL5ZHwjmOuxYE6hicdKt2vwOjLa31hLY/u3bT8s346w+DzIPZmItU=
 matrix:
   include:
-    - php: 5.6
-      env: WP_VERSION=master
-  allow_failures:
-    - php: 5.6
-  fast_finish: true
-
-# Use this to prepare the system to install prerequisites or dependencies.
-# e.g. sudo apt-get update.
-# Failures in this section will result in build status 'errored'.
-# before_install:
-
-# Use this to prepare your build for testing.
-# e.g. copy database configurations, environment variables, etc.
-# Failures in this section will result in build status 'errored'.
+  - php: 7.2
+  - php: 7.1
+  - php: 7.0
+  - php: 5.6
+  - php: 5.6
+    env: WP_PULUGIN_DEPLOY=1
+  - php: 5.6
+    env: WP_TRAVISCI=travis:phpcs
+  - php: 5.5
+  - php: 5.4
+  - php: 5.3
+    dist: precise
 before_script:
-  # Set up WordPress installation.
-  - export WP_DEVELOP_DIR=/tmp/wordpress/
-  - mkdir -p $WP_DEVELOP_DIR
-  # Use the Git mirror of WordPress.
-  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
- # Set up plugin information.
-  - plugin_slug=$(basename $(pwd))
-  - plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_slug
-  - cd ..
-  - mv $plugin_slug $plugin_dir
-  # Set up WordPress configuration.
-  - cd $WP_DEVELOP_DIR
-  - echo $WP_DEVELOP_DIR
-  - cp wp-tests-config-sample.php wp-tests-config.php
-  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
-  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
-  - sed -i "s/yourpasswordhere//" wp-tests-config.php
-  # Create WordPress database.
-  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
-  # Install CodeSniffer for WordPress Coding Standards checks.
-  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git php-codesniffer
-  # Install WordPress Coding Standards.
-  - git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wordpress-coding-standards
-  # Hop into CodeSniffer directory.
-  - cd php-codesniffer
-  # Set install path for WordPress Coding Standards.
-  # @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
-  - scripts/phpcs --config-set installed_paths ../wordpress-coding-standards
-  # Hop into plugin directory.
-  - cd $plugin_dir
-  # After CodeSniffer install you should refresh your path.
-  - phpenv rehash
+- |
+  # Remove Xdebug for a huge performance increase:
+  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
+    phpenv config-rm xdebug.ini
+  else
+    echo "xdebug.ini does not exist"
+  fi
+- |
+  # Export Composer's global bin dir to PATH:
+  composer config --list --global
+  export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
+- |
+  # Install the specified version of PHPUnit depending on the PHP version:
+  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
+    case "$TRAVIS_PHP_VERSION" in
+      7.2|7.1|7.0|nightly)
+        echo "Using PHPUnit 6.x"
+        composer global require "phpunit/phpunit:^6"
+        ;;
+      5.6|5.5|5.4|5.3)
+        echo "Using PHPUnit 4.x"
+        composer global require "phpunit/phpunit:^4"
+        ;;
+      5.2)
+        # Do nothing, use default PHPUnit 3.6.x
+        echo "Using default PHPUnit, hopefully 3.6"
+        ;;
+      *)
+        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
+        exit 1
+        ;;
+    esac
+  fi
+  if [[ "$WP_TRAVISCI" == "travis:phpcs" ]] ; then
+      composer install
+  fi
 
-# Run test script commands.
-# Default is specific to project language.
-# All commands must exit with code 0 on success. Anything else is considered failure.
+- mysql --version
+- phpenv versions
+- php --version
+- php -m
+- which phpunit
+- phpunit --version
+- curl --version
+- grunt --version
+- git --version
+- svn --version
+- locale -a
+before_install:
+- export PATH="$HOME/.composer/vendor/bin:$PATH"
+- |
+    if [[ ! -z "$WP_VERSION" ]] ; then
+      set -e
+      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
+      set +e
+    fi
 script:
-  # Search for PHP syntax errors.
-  - find . \( -name '*.php' \) -exec php -lf {} \;
-  # WordPress Coding Standards
-  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
-  # @link http://pear.php.net/package/PHP_CodeSniffer/
-  # -p flag: Show progress of the run.
-  # -s flag: Show sniff codes in all reports.
-  # -v flag: Print verbose output.
-  # -n flag: Do not print warnings. (shortcut for --warning-severity=0)
-  # -l flag: Run locally
-  # --standard: Use WordPress as the standard.
-  # --extensions: Only sniff PHP files.
-  - $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -l -p -s -v -n . --standard=phpcs.ruleset.xml --extensions=php
-  - $WP_DEVELOP_DIR/php-codesniffer/scripts/phpcs -p -s -v -n includes/ --standard=phpcs.ruleset.xml --extensions=php
-
-# Receive notifications for build results.
-# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
-notifications:
-  email: false
+  - |
+    if [[ ! -z "$WP_VERSION" ]] ; then
+      # Run the build because otherwise there will be a bunch of warnings about
+      # failed `stat` calls from `filemtime()`.
+      echo Running with the following versions:
+      php -v
+      phpunit --version
+      # Run PHPUnit tests
+      phpunit || exit 1
+      WP_MULTISITE=1 phpunit || exit 1
+    fi
+  - |
+    if [[ "$WP_TRAVISCI" == "travis:phpcs" ]] ; then
+      ./vendor/bin/phpcs -p -s -v -n --standard=./phpcs.ruleset.xml --extensions=php
+    fi
